CREATE SEQUENCE "SALES_ORDER_ID" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 161 CACHE 20 NOORDER NOCYCLE
CREATE SEQUENCE "PURCHASES_ORDER_ID" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER NOCYCLE
CREATE SEQUENCE "SALE_RETURNS_ORDER_ID" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER NOCYCLE
CREATE SEQUENCE "PURCHASE_RETURNS_ORDER_ID" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER NOCYCLE
CREATE SEQUENCE "POS_SEQUENCE" MINVALUE 1000 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1466 CACHE 20 NOORDER NOCYCLE
CREATE SEQUENCE "POS_DETAILS_SEQUENCE" MINVALUE 1000 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1020 CACHE 20 NOORDER NOCYCLE
CREATE SEQUENCE "SEQ_PURCHASE" MINVALUE 1000 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1000 CACHE 20 NOORDER NOCYCLE

CREATE TABLE "CUSTOMERS" ("CUSTOMER_ID" NUMBER, "NAME" VARCHAR2(100), "MODIFIED" TIMESTAMP (6), "CREATED" TIMESTAMP (6))  ;

CREATE TABLE "ITEMS" ("ITEM_ID" NUMBER, "CODE" VARCHAR2(60), "NAME" VARCHAR2(100), "PACK_UNIT_ID" NUMBER, "PACK_SIZE" NUMBER(8, 0), "STANDARD_UNIT_ID" NUMBER, "CREATED" TIMESTAMP (6), "MODIFIED" TIMESTAMP (6));

CREATE TABLE "ITEM_PRICES" ("ITEM_PRICE_ID" NUMBER, "ITEM_ID" NUMBER, "SALE_PRICE" NUMBER, "EFFECTIVE_FROM" DATE, "EFFECTIVE_TO" DATE, "STATUS" NUMBER(1, 0));

CREATE TABLE "PURCHASES" ("ORDER_ID" NUMBER, "INVOICE_DATE" DATE, "PARTY_ID" NUMBER, "PARTY_NAME" VARCHAR2(120), "PARTY_CONTACT" VARCHAR2(40), "TOTAL_QUANTITY" NUMBER, "TOTAL_AMOUNT" NUMBER, "OTHER_AMOUNT" NUMBER, "TOTAL_PAYBLE_AMOUNT" NUMBER, "TOTAL_PAID_AMOUNT" NUMBER, "TOTAL_DUE_AMOUNT" NUMBER, "REMARKS" VARCHAR2(1200), "CREATED_ON" DATE);

CREATE TABLE "PURCHASE_DETAILS" ("ORDER_ID" NUMBER, "ITEM_ID" NUMBER, "ITEM_NAME" VARCHAR2(160), "LOCATION" VARCHAR2(40), "UOM" VARCHAR2(20), "QUANTITY" NUMBER, "PRICE" NUMBER, "AMOUNT" NUMBER) ;

CREATE TABLE "PURCHASE_RETURNS" ("ORDER_ID" NUMBER, "INVOICE_DATE" DATE, "PARTY_ID" NUMBER, "PARTY_NAME" VARCHAR2(120), "PARTY_CONTACT" VARCHAR2(40), "TOTAL_QUANTITY" NUMBER, "TOTAL_AMOUNT" NUMBER, "OTHER_AMOUNT" NUMBER, "TOTAL_PAYBLE_AMOUNT" NUMBER, "TOTAL_PAID_AMOUNT" NUMBER, "TOTAL_DUE_AMOUNT" NUMBER, "REMARKS" VARCHAR2(1200), "CREATED_ON" DATE);

CREATE TABLE "PURCHASE_RETURN_DETAILS" ("ORDER_ID" NUMBER, "ITEM_ID" NUMBER, "ITEM_NAME" VARCHAR2(160), "LOCATION" VARCHAR2(40), "UOM" VARCHAR2(20), "QUANTITY" NUMBER, "PRICE" NUMBER, "AMOUNT" NUMBER);

CREATE TABLE "SALES" ("ORDER_ID" NUMBER, "INVOICE_DATE" DATE, "PARTY_ID" NUMBER, "PARTY_NAME" VARCHAR2(120), "PARTY_CONTACT" VARCHAR2(40), "TOTAL_QUANTITY" NUMBER, "TOTAL_AMOUNT" NUMBER, "OTHER_AMOUNT" NUMBER, "TOTAL_PAYBLE_AMOUNT" NUMBER, "TOTAL_PAID_AMOUNT" NUMBER, "TOTAL_DUE_AMOUNT" NUMBER, "REMARKS" VARCHAR2(1200), "CREATED_ON" DATE, "CURRENCY" VARCHAR2(10), "TAUX" NUMBER(15, 2));

CREATE TABLE "SALE_DETAILS" ("ORDER_ID" NUMBER, "ITEM_ID" NUMBER, "ITEM_NAME" VARCHAR2(160), "LOCATION" VARCHAR2(40), "UOM" VARCHAR2(20), "QUANTITY" NUMBER, "PRICE" NUMBER, "AMOUNT" NUMBER) ;

CREATE TABLE "SALE_RETURNS" ("ORDER_ID" NUMBER, "INVOICE_DATE" DATE, "PARTY_ID" NUMBER, "PARTY_NAME" VARCHAR2(120), "PARTY_CONTACT" VARCHAR2(40), "TOTAL_QUANTITY" NUMBER, "TOTAL_AMOUNT" NUMBER, "OTHER_AMOUNT" NUMBER, "TOTAL_PAYBLE_AMOUNT" NUMBER, "TOTAL_PAID_AMOUNT" NUMBER, "TOTAL_DUE_AMOUNT" NUMBER, "REMARKS" VARCHAR2(1200), "CREATED_ON" DATE);

CREATE TABLE "SALE_RETURN_DETAILS" ("ORDER_ID" NUMBER, "ITEM_ID" NUMBER, "ITEM_NAME" VARCHAR2(160), "LOCATION" VARCHAR2(40), "UOM" VARCHAR2(20), "QUANTITY" NUMBER, "PRICE" NUMBER, "AMOUNT" NUMBER) ;

CREATE TABLE "UOMS" ("UOM_ID" NUMBER, "NAME" VARCHAR2(60), "CREATED" TIMESTAMP (6), "MODIFIED" TIMESTAMP (6));


